### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Byteme8bit** [Rubydrag0n/BeltBalancer#1]
I had place 7 belts and 2 splitters. I had a splitter "in hand" and right clicked on a splitter when the client crashed :(

I don't see a log file so I just included as much detail as possible.

**Comment by AntonReinhard** [comment]
Yeah, I don't have a log file. I could pretty much reproduce it, there's probably something wrong with the way I'm deleting objects that are already placed.
But I'm not really doing anything new with this anymore so sorry... I'm not gonna fix it

**Comment by Byteme8bit** [comment]
No problem at all. Just thought I'd share my findings :) Great work none the less!
